#  04 Aishawariya Athawale
#  08 Pankti Fadia
#  10 Hetvi Julasana

# Cosine similarity Assignment 5

In [13]:
import numpy as np 
import pandas as pd
import re
from sklearn.feature_extraction import text

In [14]:
df_train = pd.read_csv('cosine_train.csv')
df_train.head()

,Unnamed: 0,description_x,description_y,ticker_x,ticker_y,same_security
0,0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,True
1,1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,True
2,2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,False
3,3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,True
4,4,visa inc class a,visa inc.,V,V,True

In [15]:
df_train = df_train.drop(["Unnamed: 0", "ticker_x", "ticker_y", "same_security"], axis = 1)
print('df_train:', df_train.shape)
display(df_train.head(5))

df_train: (2142, 2)

,description_x,description_y
0,first trust dow jones internet,first trust dj internet idx
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...
2,vanguard small cap index adm,vanguard small-cap index fund inst
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...
4,visa inc class a,visa inc.

In [16]:
vectorizer = text.TfidfVectorizer()

def cosine_sim(test1, test2):
    tfidf = vectorizer.fit_transform([test1, test2])
    result = ((tfidf * tfidf.T).A)[0,1]
    return result
    
def cosine_sim_df(df_data):
    col1 = 'description_x'
    col2 = 'description_y'
    df_data[col1] = df_data[col1].str.replace(r'\d', '')
    df_data[col2] = df_data[col2].str.replace(r'\d', '')
    
    df_data['cos_sim'] = 0
    df_data['cos_sim'] = df_data.apply(
        lambda x: cosine_sim(x[col1], x[col2]), axis=1)
    return df_data

In [17]:
df_result = cosine_sim_df(df_train)
display(df_result)

,description_x,description_y,cos_sim
0,first trust dow jones internet,first trust dj internet idx,0.431613
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,0.527072
2,vanguard small cap index adm,vanguard small-cap index fund inst,0.580333
3,duke energy corp new com new isin #us sedol #b...,duke energy corp new com new isin #usc sedol #...,0.716812
4,visa inc class a,visa inc.,0.709297
...,...,...,...
2137,delta air lines inc com,delta air lines inc dela new,0.580333
2138,cognizant tech solutns a,cognizant tech solutions corp,0.411207
2139,pimco investment grade corporate bond fund - c...,fid conservative income bond fund,0.206137
2140,eli lilly & co com,lilly eli &co com npv,0.818180
2141,dfa comm strategy i,dfa commodity strategy port,0.411207